apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    app: {{ .Values.selector.app }}
    type: {{ .Values.selector.type }}
spec:
  containers:
    - name: nginx-container
      image: "{{ .Values.podImage.repository }}:{{ .Values.podImage.tag }}"
      imagePullPolicy: {{ .Values.podImage.pullPolicy }}
