apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Values.selector.app }}
    type: {{ .Values.selector.type }}
